import { Inter as FontSans } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

import { cn } from "@/lib/utils";
import Home from "./page";
import { GalleryHorizontal, HomeIcon, Phone, User } from "lucide-react";
import { FloatingNav } from "@/components/ui/floating-navbar";
import Footer from "@/components/ui/footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

const navItems = [
  {
    name: "Home",
    link: "#home",
    icon: <HomeIcon className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "Projects",
    link: "#projects",
    icon: <GalleryHorizontal className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "Contact",
    link: "#contact",
    icon: <Phone className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "About",
    link: "#about",
    icon: <User className="h-4 w-4 text-neutral-500 dark:text-white" />,
  }
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
      <FloatingNav navItems={navItems}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}